
development:
  adapter: postgresql
  database: epicodus_reworked_development

test:
  adapter: postgresql
  database: epicodus_reworked_test

production:
  adapter: postgresql
  encoding: unicode
  database: epicodus_reworked_production
  pool: 5
  username: epicodus_reworked
  password:
